name: Integration test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./FrontEnd/Sailfish-EndToEndTest/gradlew -b ./FrontEnd/Sailfish-EndToEndTest/build.gradle clean iT
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: report
        path: ./FrontEnd/Sailfish-EndToEndTest/build/test-results/
#     - name: Google Chat Notification
#       uses: Co-qn/google-chat-notification@releases/v1
#       with:
#         name: Build
#         url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
#         status: ${{ job.status }}
#       if: always()
